- name: Filter
  hosts: localhost
  vars:
    URL: https://nginx.org/download/nginx-1.25.3.zip
  tasks:
    - name: Filter
      ansible.builtin.unarchive:
        src: "{{ URL }}"
        dest: /tmp
        remote_src: yes

    - name: Url split
      ansible.builtin.debug:
        msg: "{{ URL | splitext('/') }}"
